par(lwd=2)
par(cex=2)
daf <- density(l$Affluent$KWH, na.rm = T)
plot(daf, xlim=c(0.0,1.5), ylim=c(0.0,8.0), main="Density of 3 groups", col="red")
par(new=T)
dad <- density(l$Adversity$KWH, na.rm = T)
plot(dad, main="", xlab="", ylab="", xlim=c(0.0,1.5), ylim=c(0.0,8.0), col="blue")
par(new=T)
dco <- density(l$Comfortable$KWH, na.rm = T)
plot(dco, main="", xlab="", ylab="", xlim=c(0.0,1.5), ylim=c(0.0,8.0), col="green")
par(new=F)